const norm=v=>String(v||'').trim().toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ');
const arr=v=>Array.isArray(v)?v:[];
const map=v=>new Map(arr(v).filter(Boolean).map(x=>[norm(x),String(x).trim()]));
const intersect=(a,b)=>{const A=map(a),B=map(b),out=[];for(const[k,v]of A)if(B.has(k))out.push(B.get(k)||v);return out};
const INSTITUTION_ALIASES={usp:'universidade de sao paulo','universidade sao paulo':'universidade de sao paulo',unesp:'universidade estadual paulista julio de mesquita filho','universidade estadual paulista':'universidade estadual paulista julio de mesquita filho',unicamp:'universidade estadual de campinas',ufrj:'universidade federal do rio de janeiro',ufmg:'universidade federal de minas gerais',ufba:'universidade federal da bahia',ufpe:'universidade federal de pernambuco',ufc:'universidade federal do ceara',ufpr:'universidade federal do parana',ufrgs:'universidade federal do rio grande do sul',unb:'universidade de brasilia','puc sp':'pontificia universidade catolica de sao paulo','puc-sp':'pontificia universidade catolica de sao paulo','puc rio':'pontificia universidade catolica do rio de janeiro','puc-rio':'pontificia universidade catolica do rio de janeiro',pucrs:'pontificia universidade catolica do rio grande do sul',ita:'instituto tecnologico de aeronautica',ime:'instituto militar de engenharia',fgv:'fundacao getulio vargas'};
const COURSE_ALIASES={adm:'administracao',cc:'ciencia da computacao','eng civil':'engenharia civil',ri:'relacoes internacionais',psico:'psicologia',med:'medicina'};
function canonicalInstitution(v){const n=norm(v);return INSTITUTION_ALIASES[n]||n}
function canonicalCourse(v){const n=norm(v);return COURSE_ALIASES[n]||n}
export function compatibility(me,person){if(!me||!person)return{score:0,reasons:[],give:[],receive:[],shared:[]};const receive=intersect(me.need_help,person.can_help),give=intersect(me.can_help,person.need_help),shared=intersect(me.interests,person.interests),sameInstitution=!!me.institution&&canonicalInstitution(me.institution)===canonicalInstitution(person.institution),sameCity=!!me.city&&norm(me.city)===norm(person.city),sameCourse=!!me.course_or_role&&canonicalCourse(me.course_or_role)===canonicalCourse(person.course_or_role);let score=0;score+=Math.min(42,receive.length*22);score+=Math.min(32,give.length*17);score+=Math.min(16,shared.length*8);if(sameInstitution)score+=6;if(sameCity)score+=4;if(sameCourse)score+=4;if(!score){const broad=intersect([...(me.interests||[]),...(me.can_help||[]),...(me.need_help||[])],[...(person.interests||[]),...(person.can_help||[]),...(person.need_help||[])]);score=Math.min(24,broad.length*8)}score=Math.min(100,score);const reasons=[];if(receive.length)reasons.push(`${person.name?.split(' ')[0]||'Esta pessoa'} pode ajudar em ${receive.slice(0,2).join(' e ')}`);if(give.length)reasons.push(`Você pode ajudar em ${give.slice(0,2).join(' e ')}`);if(shared.length)reasons.push(`Interesse em comum: ${shared.slice(0,2).join(' e ')}`);if(sameInstitution)reasons.push('Vocês têm a mesma instituição');else if(sameCourse)reasons.push('Vocês têm o mesmo curso ou área profissional');else if(sameCity)reasons.push('Vocês estão na mesma cidade');return{score,reasons:reasons.slice(0,4),give,receive,shared}}
export function rankPeople(me,people=[]){return people.map(person=>({...person,compatibility:compatibility(me,person)})).sort((a,b)=>b.compatibility.score-a.compatibility.score||String(a.name||'').localeCompare(String(b.name||''),'pt-BR'))}
