import React,{useEffect,useRef,useState}from'react';
import{useNavigate,useParams}from'react-router-dom';
import{supabase}from'../lib/supabase.js';
import{ArrowLeft,Save,Image as ImageIcon,Video,X}from'lucide-react';

const CATEGORIES=['Ciências Exatas','Ciências Humanas','Saúde','Tecnologia','Engenharias','Direito','Educação','Idiomas','Artes e Design','Negócios e Mercado','Finanças e Economia','Carreira','Pesquisa','Outro'];
const parseKeywords=v=>[...new Set(String(v||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,8))];

export default function EditForumPost({session}){
  const{postId}=useParams(),navigate=useNavigate(),fileRef=useRef();
  const[post,setPost]=useState(null),[title,setTitle]=useState(''),[body,setBody]=useState(''),[area,setArea]=useState(''),[keywords,setKeywords]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[mediaFile,setMediaFile]=useState(null),[preview,setPreview]=useState(''),[removeMedia,setRemoveMedia]=useState(false);
  useEffect(()=>{load()},[postId]);useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview)},[preview]);
  async function load(){setLoading(true);const{data,error:e}=await supabase.from('forum_posts').select('*').eq('id',postId).maybeSingle();if(e||!data){setError('Publicação não encontrada.');setLoading(false);return}if(data.user_id!==session.user.id){setError('Você não pode editar esta publicação.');setLoading(false);return}setPost(data);setTitle(data.title||'');setBody(data.body||'');setArea(data.area||'');setKeywords((data.keywords||[]).join(', '));setRemoveMedia(false);setLoading(false)}
  function chooseMedia(file){if(!file)return;if(!file.type.startsWith('image/')&&!file.type.startsWith('video/'))return setError('Escolha uma imagem ou vídeo válido.');if(file.size>50*1024*1024)return setError('A mídia deve ter no máximo 50 MB.');if(preview)URL.revokeObjectURL(preview);setMediaFile(file);setPreview(URL.createObjectURL(file));setRemoveMedia(false);setError('')}
  function clearNew(){if(preview)URL.revokeObjectURL(preview);setPreview('');setMediaFile(null)}
  async function uploadMedia(){if(!mediaFile)return null;const ext=(mediaFile.name.split('.').pop()||'bin').toLowerCase(),path=`${session.user.id}/${Date.now()}-${Math.random().toString(36).slice(2)}.${ext}`;const{error:e}=await supabase.storage.from('forum-media').upload(path,mediaFile,{contentType:mediaFile.type,cacheControl:'3600'});if(e)throw e;const{data}=supabase.storage.from('forum-media').getPublicUrl(path);return{media_url:data.publicUrl,media_type:mediaFile.type.startsWith('video/')?'video':'image'} }
  async function save(){const tags=parseKeywords(keywords);if(title.trim().length<5||body.trim().length<20||!area||!tags.length)return setError('Preencha título, texto, macroárea e pelo menos 1 palavra-chave.');setSaving(true);setError('');try{let media={};if(removeMedia)media={media_url:null,media_type:null};else if(mediaFile)media=await uploadMedia();const{error:e}=await supabase.from('forum_posts').update({title:title.trim(),body:body.trim(),area,keywords:tags,updated_at:new Date().toISOString(),...media}).eq('id',postId).eq('user_id',session.user.id);if(e)throw e;navigate(`/forum/post/${postId}`,{replace:true})}catch(e){setError('Não foi possível salvar: '+e.message);setSaving(false)}}
  if(loading)return <div style={s.state}>Carregando publicação...</div>;
  if(error&&!post)return <div style={s.state}><h3>{error}</h3><button className="btn-primary" onClick={()=>navigate('/forum')}>Voltar ao Fórum</button></div>;
  const currentVisible=post?.media_url&&!removeMedia&&!mediaFile;
  return <div style={s.page}><header style={s.header}><button aria-label="Voltar" style={s.back} onClick={()=>navigate(-1)}><ArrowLeft size={18}/></button><div><small>FÓRUM STUDYMATCH</small><h2>Editar publicação</h2></div></header><main style={s.card}><label style={s.label}>Macroárea</label><select value={area} onChange={e=>setArea(e.target.value)}>{CATEGORIES.map(x=><option key={x}>{x}</option>)}</select><label style={s.label}>Título</label><input value={title} maxLength={140} onChange={e=>setTitle(e.target.value)}/><label style={s.label}>Texto</label><textarea rows={9} value={body} maxLength={2500} onChange={e=>setBody(e.target.value)}/><label style={s.label}>Palavras-chave / tags</label><input value={keywords} onChange={e=>setKeywords(e.target.value)} placeholder="Ex.: programação, React, JavaScript"/><small style={s.hint}>Separe por vírgulas. Máximo de 8.</small><label style={s.label}>Mídia</label>{currentVisible&&<div style={s.mediaBox}>{post.media_type==='video'?<video controls src={post.media_url} style={s.media}/>:<img src={post.media_url} alt="Mídia atual" style={s.media}/>}<button style={s.remove} onClick={()=>setRemoveMedia(true)}><X size={14}/>Remover mídia</button></div>}{mediaFile&&<div style={s.mediaBox}>{mediaFile.type.startsWith('video/')?<video controls src={preview} style={s.media}/>:<img src={preview} alt="Nova mídia" style={s.media}/>}<button style={s.remove} onClick={clearNew}><X size={14}/>Cancelar substituição</button></div>}{removeMedia&&!mediaFile&&<div style={s.removed}>A mídia será removida ao salvar.</div>}<input ref={fileRef} hidden type="file" accept="image/*,video/mp4,video/webm,video/quicktime" onChange={e=>{chooseMedia(e.target.files?.[0]);e.target.value=''}}/><button style={s.mediaBtn} onClick={()=>fileRef.current?.click()}><ImageIcon size={16}/><Video size={16}/>{post?.media_url&&!removeMedia?'Substituir imagem ou vídeo':'Adicionar imagem ou vídeo'}</button>{error&&<div style={s.error}>{error}</div>}<div style={s.actions}><button style={s.cancel} onClick={()=>navigate(-1)}>Cancelar</button><button className="btn-primary" disabled={saving} onClick={save}><Save size={16}/>{saving?'Salvando...':'Salvar alterações'}</button></div></main></div>
}
const s={page:{maxWidth:650,margin:'0 auto',paddingBottom:100},header:{display:'flex',alignItems:'center',gap:12,padding:'20px 16px',background:'linear-gradient(135deg,#1456A0,#0D8B83)',color:'white',borderRadius:'0 0 24px 24px'},back:{width:38,height:38,borderRadius:'50%',background:'#ffffff22',color:'white',display:'grid',placeItems:'center'},card:{margin:14,background:'white',padding:18,borderRadius:20,boxShadow:'0 8px 26px rgba(20,86,160,.08)',display:'flex',flexDirection:'column',gap:9},label:{fontSize:11,fontWeight:800,color:'#334155',marginTop:4},hint:{fontSize:10,color:'#718096'},error:{background:'#FFF1F2',color:'#D83A4A',padding:11,borderRadius:11,fontSize:12},actions:{display:'grid',gridTemplateColumns:'1fr 1.35fr',gap:9,marginTop:8},cancel:{borderRadius:14,background:'#EEF2F6',color:'#526176',fontWeight:800},state:{minHeight:'70vh',display:'grid',placeItems:'center',textAlign:'center',padding:25},mediaBox:{display:'grid',gap:7},media:{width:'100%',maxHeight:300,objectFit:'contain',borderRadius:13,background:'#F1F5F9'},mediaBtn:{display:'flex',alignItems:'center',justifyContent:'center',gap:7,padding:11,borderRadius:12,background:'#EEF5FF',color:'#1456A0',fontWeight:700},remove:{justifySelf:'start',display:'flex',alignItems:'center',gap:4,background:'transparent',color:'#B42332',fontSize:11,fontWeight:700},removed:{background:'#FFF5F5',color:'#9C3B46',padding:10,borderRadius:11,fontSize:11}};