import React,{useEffect,useState}from'react';
import{useNavigate}from'react-router-dom';
import{supabase}from'../lib/supabase.js';
import CollapsibleText from'../components/CollapsibleText.jsx';
import useAppDialog from'../components/useAppDialog.jsx';
import{ArrowLeft,Edit3,Trash2,Save,X,Tag,Image as ImageIcon,Video,ExternalLink}from'lucide-react';

const CATEGORIES=['Ciências Exatas','Ciências Humanas','Saúde','Tecnologia','Engenharias','Direito','Educação','Idiomas','Artes e Design','Negócios e Mercado','Finanças e Economia','Carreira','Pesquisa','Outro'];
const parseKeywords=v=>[...new Set(String(v||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,8))];

export default function MyPosts({session}){
  const navigate=useNavigate();
  const[posts,setPosts]=useState([]),[loading,setLoading]=useState(true),[editing,setEditing]=useState(null),[title,setTitle]=useState(''),[body,setBody]=useState(''),[area,setArea]=useState(''),[keywords,setKeywords]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
  const{confirmDialog,Dialog}=useAppDialog();
  useEffect(()=>{load()},[]);
  async function load(){setLoading(true);const{data,error:e}=await supabase.from('forum_posts').select('*').eq('user_id',session.user.id).order('created_at',{ascending:false});if(e)setError(e.message);setPosts(data||[]);setLoading(false)}
  function startEdit(p){setEditing(p);setTitle(p.title||'');setBody(p.body||'');setArea(p.area||'');setKeywords((p.keywords||[]).join(', '));setError('')}
  function closeEdit(){setEditing(null);setError('')}
  async function save(){const ks=parseKeywords(keywords);if(title.trim().length<5||body.trim().length<20||!area||!ks.length)return setError('Preencha título, conteúdo, macroárea e pelo menos uma palavra-chave.');setSaving(true);const payload={title:title.trim(),body:body.trim(),area,keywords:ks,edited_at:new Date().toISOString()};const{error:e}=await supabase.from('forum_posts').update(payload).eq('id',editing.id).eq('user_id',session.user.id);setSaving(false);if(e)return setError('Não foi possível editar: '+e.message);setEditing(null);await load()}
  async function remove(p){const ok=await confirmDialog('Excluir esta publicação? As respostas também serão removidas.','Excluir publicação');if(!ok)return;const{error:e}=await supabase.from('forum_posts').delete().eq('id',p.id).eq('user_id',session.user.id);if(e)return setError(e.message);await load()}
  return <div style={s.page}><header style={s.header}><button onClick={()=>navigate(-1)} style={s.back}><ArrowLeft size={19}/></button><div><small>FÓRUM</small><h2>Minhas publicações</h2><p>Edite texto, título, área e palavras-chave das suas postagens.</p></div></header>{error&&!editing&&<div style={s.error}>{error}</div>}<main style={s.list}>{loading?<div style={s.state}>Carregando...</div>:!posts.length?<div style={s.state}>Você ainda não publicou no Fórum.</div>:posts.map(p=><article key={p.id} style={s.card}><div style={s.meta}><span>{p.area}</span><small>{new Date(p.created_at).toLocaleDateString('pt-BR')}{p.edited_at?' · Editado':''}</small></div><h3>{p.title}</h3><CollapsibleText text={p.body} limit={300} style={s.body}/>{(p.keywords||[]).length>0&&<div style={s.tags}>{p.keywords.map(k=><span key={k}><Tag size={11}/>{k}</span>)}</div>}{p.media_url&&p.media_type==='image'&&<img src={p.media_url} style={s.media}/>} {p.media_url&&p.media_type==='video'&&<video controls src={p.media_url} style={s.media}/>}<div style={s.actions}><button style={s.view} onClick={()=>navigate(`/forum/post/${p.id}`)}><ExternalLink size={15}/>Abrir</button><button style={s.edit} onClick={()=>startEdit(p)}><Edit3 size={15}/>Editar</button><button style={s.delete} onClick={()=>remove(p)}><Trash2 size={15}/>Excluir</button></div></article>)}</main>{editing&&<div style={s.overlay}><section style={s.modal}><button style={s.close} onClick={closeEdit}><X size={18}/></button><div><small style={s.eyebrow}>EDITAR PUBLICAÇÃO</small><h2>{editing.title}</h2></div><select value={area} onChange={e=>setArea(e.target.value)}><option value="">Macroárea</option>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select><input value={title} maxLength={140} onChange={e=>setTitle(e.target.value)} placeholder="Título"/><textarea rows={8} maxLength={2500} value={body} onChange={e=>setBody(e.target.value)} placeholder="Conteúdo"/><div><label style={s.label}>Palavras-chave</label><input value={keywords} onChange={e=>setKeywords(e.target.value)} placeholder="Ex.: e-commerce, SEO, física quântica"/><small style={s.hint}>Separe por vírgulas. Máximo de 8.</small></div>{editing.media_url&&<div style={s.mediaNotice}>{editing.media_type==='image'?<ImageIcon size={15}/>:<Video size={15}/>}A mídia original será mantida.</div>}{error&&<div style={s.error}>{error}</div>}<button className="btn-primary" disabled={saving} onClick={save}><Save size={16}/>{saving?'Salvando...':'Salvar edição'}</button></section></div>}<Dialog/></div>
}
const s={page:{maxWidth:680,margin:'0 auto',paddingBottom:100},header:{position:'relative',background:'linear-gradient(135deg,#1456A0,#0D8B83)',color:'white',padding:'26px 18px 20px',borderRadius:'0 0 24px 24px'},back:{position:'absolute',left:12,top:14,width:36,height:36,borderRadius:'50%',background:'#ffffff22',color:'white',display:'grid',placeItems:'center'},list:{display:'grid',gap:12,padding:14},card:{background:'white',padding:16,borderRadius:18,boxShadow:'0 5px 18px #082a5510'},meta:{display:'flex',justifyContent:'space-between',fontSize:10,color:'#718096',marginBottom:8},body:{fontSize:13,lineHeight:1.55,color:'#334155'},tags:{display:'flex',gap:5,flexWrap:'wrap',marginTop:10},actions:{display:'flex',gap:7,marginTop:13,paddingTop:11,borderTop:'1px solid #EEF2F6'},view:{display:'flex',gap:5,alignItems:'center',padding:'8px 10px',borderRadius:10,background:'#F1F5F9',color:'#526176',fontWeight:700},edit:{display:'flex',gap:5,alignItems:'center',padding:'8px 10px',borderRadius:10,background:'#EAF3FF',color:'#1456A0',fontWeight:800},delete:{display:'flex',gap:5,alignItems:'center',padding:'8px 10px',borderRadius:10,background:'#FFF1F2',color:'#C53B4B',fontWeight:700},media:{width:'100%',maxHeight:380,objectFit:'contain',borderRadius:13,marginTop:10,background:'#07111D'},state:{background:'white',padding:30,borderRadius:18,textAlign:'center',color:'#718096'},overlay:{position:'fixed',inset:0,zIndex:3500,background:'#06182dcc',display:'grid',placeItems:'center',padding:14},modal:{position:'relative',width:'100%',maxWidth:520,maxHeight:'92vh',overflowY:'auto',background:'white',borderRadius:22,padding:20,display:'grid',gap:11,boxShadow:'0 25px 80px #0004'},close:{position:'absolute',right:10,top:10,width:34,height:34,borderRadius:'50%',background:'#F1F5F9',color:'#526176'},eyebrow:{fontSize:9,fontWeight:800,letterSpacing:1.2,color:'#10A77B'},label:{fontSize:11,fontWeight:800,color:'#334155'},hint:{display:'block',fontSize:10,color:'#94A3B8',marginTop:4},mediaNotice:{display:'flex',alignItems:'center',gap:6,padding:10,borderRadius:11,background:'#F0F7F5',color:'#08785A',fontSize:11},error:{margin:14,padding:10,borderRadius:12,background:'#FFF1F2',color:'#B42332',fontSize:12}};