import React,{useEffect,useState}from'react';
import{useParams}from'react-router-dom';
import{supabase}from'../lib/supabase.js';

const BASE='https://matchworking.vercel.app';
const clip=(v,n)=>String(v||'').replace(/\s+/g,' ').trim().slice(0,n);
export default function PublicForumPost(){
 const{postId}=useParams(),[post,setPost]=useState(null),[loading,setLoading]=useState(true);
 useEffect(()=>{let alive=true;(async()=>{const{data,error}=await supabase.rpc('get_public_forum_post',{p_post_id:postId});if(!alive)return;const p=Array.isArray(data)?data[0]:data;if(!error&&p){setPost(p);const title=`${clip(p.title,70)} | Matchworking`,desc=clip(p.body||`${p.author_name} publicou sobre ${p.area||'conhecimento'} no Matchworking.`,155),url=`${BASE}/publicacao/${p.id}`;document.title=title;const set=(sel,attr,val)=>{let e=document.head.querySelector(sel);if(!e){e=document.createElement('meta');if(sel.includes('property='))e.setAttribute('property',sel.match(/property="([^"]+)/)?.[1]||'');else e.setAttribute('name',sel.match(/name="([^"]+)/)?.[1]||'');document.head.appendChild(e)}e.setAttribute(attr,val)};set('meta[name="description"]','content',desc);set('meta[name="robots"]','content','index,follow,max-image-preview:large');set('meta[property="og:title"]','content',title);set('meta[property="og:description"]','content',desc);set('meta[property="og:url"]','content',url);let c=document.head.querySelector('link[rel="canonical"]');if(!c){c=document.createElement('link');c.rel='canonical';document.head.appendChild(c)}c.href=url}else{document.title='Publicação indisponível | Matchworking'}setLoading(false)})();return()=>{alive=false}},[postId]);
 if(loading)return <main style={s.state}>Carregando publicação...</main>;
 if(!post)return <main style={s.state}><div><b style={s.brand}>Matchworking</b><h1>Publicação indisponível</h1><p>Esta publicação não está disponível publicamente.</p><a href="/sobre">Conhecer o Matchworking</a></div></main>;
 return <main style={s.page}><header><a href="/sobre" style={s.brand}>Match<span style={s.green}>working</span></a></header><article style={s.card}><div style={s.meta}>{post.area||'Comunidade de conhecimento'} · {new Date(post.created_at).toLocaleDateString('pt-BR')}</div><h1 style={s.h1}>{post.title}</h1><div style={s.author}>{post.author_avatar_url&&<img src={post.author_avatar_url} alt="" style={s.avatar}/>}<div><b>{post.author_name||'Membro do Matchworking'}</b>{post.author_username&&<small style={s.handle}>@{post.author_username}</small>}</div></div><div style={s.body}>{post.body}</div>{post.media_url&&post.media_type==='image'&&<img src={post.media_url} alt="Imagem da publicação" style={s.media}/>} {(post.keywords||[]).length>0&&<div style={s.tags}>{post.keywords.map(k=><span key={k} style={s.tag}>{k}</span>)}</div>}</article><section style={s.cta}><h2>Conhecimento gera conexões.</h2><p>Entre no Matchworking para participar da conversa, encontrar pessoas e construir novas colaborações.</p><a href="/register" style={s.button}>Entrar no Matchworking</a></section></main>
}
const s={page:{maxWidth:820,margin:'0 auto',padding:'34px 20px 80px',fontFamily:'Inter,Arial,sans-serif',color:'#0B2532'},state:{minHeight:'100vh',display:'grid',placeItems:'center',padding:30,textAlign:'center',fontFamily:'Inter,Arial,sans-serif',background:'#F2F5F4'},brand:{fontSize:22,fontWeight:900,color:'#153C52',textDecoration:'none'},green:{color:'#169B82'},card:{marginTop:44,background:'#fff',border:'1px solid #DCE6E3',borderRadius:16,padding:'clamp(22px,5vw,46px)'},meta:{fontSize:12,fontWeight:800,color:'#169B82',textTransform:'uppercase',letterSpacing:.6},h1:{fontSize:'clamp(30px,5vw,48px)',lineHeight:1.08,letterSpacing:'-.035em',margin:'13px 0 24px'},author:{display:'flex',alignItems:'center',gap:10,paddingBottom:24,borderBottom:'1px solid #E6ECEA'},avatar:{width:42,height:42,borderRadius:'50%',objectFit:'cover'},handle:{display:'block',color:'#718087',marginTop:2},body:{whiteSpace:'pre-wrap',fontSize:17,lineHeight:1.75,color:'#344D57',paddingTop:28},media:{width:'100%',maxHeight:620,objectFit:'contain',marginTop:26,borderRadius:12},tags:{display:'flex',gap:7,flexWrap:'wrap',marginTop:26},tag:{background:'#EDF6F3',color:'#147D69',padding:'6px 10px',borderRadius:14,fontSize:12,fontWeight:700},cta:{marginTop:18,background:'#0B2532',color:'#fff',borderRadius:16,padding:'28px 30px'},button:{display:'inline-block',marginTop:8,background:'#169B82',color:'#fff',padding:'12px 16px',borderRadius:9,textDecoration:'none',fontWeight:800}};
