const norm=v=>String(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ');
const distance=(a,b)=>{a=norm(a);b=norm(b);const m=a.length,n=b.length,d=Array.from({length:m+1},()=>Array(n+1).fill(0));for(let i=0;i<=m;i++)d[i][0]=i;for(let j=0;j<=n;j++)d[0][j]=j;for(let i=1;i<=m;i++)for(let j=1;j<=n;j++)d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return d[m][n]};
const score=(q,name,acronym='')=>{const a=norm(q),b=norm(`${name} ${acronym}`);if(b.includes(a)||a.includes(b))return 100;const aq=a.split(' '),bw=b.split(' '),overlap=aq.filter(x=>bw.some(y=>y===x||distance(x,y)<=Math.max(1,Math.floor(x.length*.2)))).length;return Math.round((1-distance(a,b)/Math.max(a.length,b.length))*55+(overlap/Math.max(aq.length,bw.length))*45)};
const BRAZIL_FALLBACK=[
['Universidade de São Paulo','USP','São Paulo'],['Universidade Estadual Paulista Júlio de Mesquita Filho','UNESP','São Paulo'],['Universidade Estadual de Campinas','UNICAMP','Campinas'],['Universidade Federal do Rio de Janeiro','UFRJ','Rio de Janeiro'],['Universidade Federal de Minas Gerais','UFMG','Belo Horizonte'],['Universidade Federal da Bahia','UFBA','Salvador'],['Universidade Federal de Pernambuco','UFPE','Recife'],['Universidade Federal do Ceará','UFC','Fortaleza'],['Universidade Federal do Paraná','UFPR','Curitiba'],['Universidade Federal do Rio Grande do Sul','UFRGS','Porto Alegre'],['Universidade de Brasília','UnB','Brasília'],['Pontifícia Universidade Católica de São Paulo','PUC-SP','São Paulo'],['Pontifícia Universidade Católica do Rio de Janeiro','PUC-Rio','Rio de Janeiro'],['Pontifícia Universidade Católica do Rio Grande do Sul','PUCRS','Porto Alegre'],['Universidade Presbiteriana Mackenzie','Mackenzie','São Paulo'],['Fundação Getulio Vargas','FGV','São Paulo'],['Instituto Tecnológico de Aeronáutica','ITA','São José dos Campos'],['Instituto Militar de Engenharia','IME','Rio de Janeiro']
];
const ALIASES={'universidade sao paulo':'USP','universidade de sao paulo':'USP','usp':'USP','unesp':'UNESP','universidade estadual paulista':'UNESP','unicamp':'UNICAMP','unb':'UnB','universidade brasilia':'UnB'};
function fallback(q){const alias=ALIASES[norm(q)],list=BRAZIL_FALLBACK.map(([name,acronym,city],i)=>({id:`br-${norm(acronym).replace(/\s/g,'-')}-${i}`,name,acronym,city,country:'BR',verified:true,source:'catalog',score:alias&&norm(acronym)===norm(alias)?120:score(q,name,acronym)}));return list.filter(x=>x.score>=38).sort((a,b)=>b.score-a.score).slice(0,8)}
export default async function handler(req,res){res.setHeader('Cache-Control','s-maxage=86400, stale-while-revalidate=604800');const q=String(req.query?.q||'').trim();if(q.length<2)return res.status(200).json({results:[]});let results=[];try{const url=`https://api.ror.org/v2/organizations?query=${encodeURIComponent(q)}&page=1`;const r=await fetch(url,{headers:{Accept:'application/json','User-Agent':'Matchworking/1.0'}});if(r.ok){const j=await r.json();for(const item of j.items||[]){const loc=(item.locations||[])[0],country=loc?.geonames_details?.country_code||'';if(country!=='BR')continue;const names=item.names||[],display=names.find(n=>n.types?.includes('ror_display'))?.value||names.find(n=>n.types?.includes('label'))?.value||names[0]?.value;const acronym=names.find(n=>n.types?.includes('acronym'))?.value||'';if(display)results.push({id:item.id,name:display,acronym,city:loc?.geonames_details?.name||'',country,verified:true,source:'ROR',score:score(q,display,acronym)})}}}catch{}
const seen=new Set();results=[...fallback(q),...results].sort((a,b)=>(b.score||0)-(a.score||0)).filter(x=>{const k=norm(x.name);if(seen.has(k))return false;seen.add(k);return true});return res.status(200).json({results:results.slice(0,10).map(({score,...x})=>x)})}
